version: '3.8'

services:
  db:
    image: postgres:17
    restart: unless-stopped
    shm_size: '128mb'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # Consider removing this if not needed externally
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'

  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - "8080:8080" # Consider restricting access
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '256M'
  
volumes:
  postgres-data:
    driver: local
    # Consider adding options for backups or specific storage drivers

networks:
  backend:
    driver: bridge

# Optional: Use secrets for sensitive data
secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
